map("n", "<c-h>", "<c-w>h")
map("n", "<c-l>", "<c-w>l")
map("n", "gh", "0")
map("n", "gs", "_")
map("n", "gl", "$")
map("n", "ge", "G")
map("n", "<c-s>", ":w<cr>")
map("n", "<c-w>", ":x<cr>")
map("n", "q:", "<nop>")
map('n', '<c-q>', ':qa<cr>')
map('n', '<c-\\>', ':vs<cr>')
map('n', 'U', '<c-r>')

map('t', '<c-j>', '<c-\\><c-n><cmd>ToggleTerm<cr>')
map('n', '<c-j>', '<cmd>ToggleTerm<cr><esc>i')

-- map("n", "w", "vw")
-- map("v", "w", "vw")
-- map("n", "b", "vb")
-- map("v", "b", "vb")
